export const POST_LOGIN="POST_LOGIN";
export const POST_LOGIN_SUCCESS="POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED="POST_LOGIN_FAILED";

export const POST_REFRESH="POST_REFRESH";
export const POST_REFRESH_SUCCESS="POST_REFRESH_SUCCESS";
export const POST_REFRESH_FAILED="POST_REFRESH_FAILED";